import {
  Wand2,
  Code,
  Key,
  LinkIcon,
  Clock,
  Search,
  GitCompare,
  Shield,
  Fingerprint,
  Hash,
  Type,
  Send,
  Grid,
  Palette,
  Eye,
  QrCode,
  FileText,
  Network,
  Database,
  FileCode,
  Calculator,
  BarChart,
  FileCode2,
  Replace,
  List,
  Scissors,
  Table,
  Lock,
  FileKey,
  Archive,
  FileImage
} from 'lucide-react';

export const tools = [
  { id: 'smart-paste', name: 'Smart Paste', icon: Wand2, category: 'featured', description: 'Automatically detect and format pasted content' },
  { id: 'data-visualization', name: 'Data Visualization', icon: Network, category: 'featured', description: 'Visualize JSON, XML, YAML, and CSV data interactively' },
  { id: 'json-formatter', name: 'JSON Formatter', icon: Code, category: 'converters', description: 'Format, validate, and minify JSON data' },
  { id: 'base64-tool', name: 'Base64 Encoder', icon: Key, category: 'converters', description: 'Encode and decode Base64 strings' },
  { id: 'url-encoder', name: 'URL Encoder', icon: LinkIcon, category: 'converters', description: 'Encode and decode URLs' },
  { id: 'timestamp-converter', name: 'Timestamp Converter', icon: Clock, category: 'converters', description: 'Convert Unix timestamps to dates' },
  { id: 'regex-tester', name: 'Regex Tester', icon: Search, category: 'validation', description: 'Test and debug regular expressions' },
  { id: 'text-diff', name: 'Text Diff Checker', icon: GitCompare, category: 'validation', description: 'Compare two texts and highlight differences' },
  { id: 'jwt-debugger', name: 'JWT Debugger', icon: Shield, category: 'validation', description: 'Decode and verify JWT tokens' },
  { id: 'uuid-generator', name: 'UUID Generator', icon: Fingerprint, category: 'generators', description: 'Generate unique identifiers' },
  { id: 'hash-generator', name: 'Hash Generator', icon: Hash, category: 'generators', description: 'Generate MD5, SHA1, SHA256 hashes' },
  { id: 'lorem-generator', name: 'Lorem Ipsum', icon: Type, category: 'generators', description: 'Generate placeholder text' },
  { id: 'password-generator', name: 'Password Generator', icon: Shield, category: 'generators', description: 'Generate secure passwords' },
  { id: 'http-client', name: 'HTTP Client', icon: Send, category: 'network', description: 'Make HTTP requests and test APIs' },
  { id: 'css-grid-generator', name: 'CSS Grid Generator', icon: Grid, category: 'design', description: 'Generate CSS Grid layouts visually' },
  { id: 'color-palette', name: 'Color Palette', icon: Palette, category: 'design', description: 'Generate beautiful color schemes' },
  { id: 'color-converter', name: 'Color Converter', icon: Palette, category: 'design', description: 'Convert between color formats' },
  { id: 'box-shadow-generator', name: 'Box Shadow', icon: Eye, category: 'design', description: 'Create CSS box shadows visually' },
  { id: 'text-case-converter', name: 'Text Case', icon: Type, category: 'text', description: 'Convert text between different cases' },
  { id: 'qr-code-generator', name: 'QR Code', icon: QrCode, category: 'generators', description: 'Generate QR codes for any text' },
  { id: 'csv-converter', name: 'CSV Converter', icon: FileText, category: 'converters', description: 'Convert CSV to JSON and vice versa' },
  { id: 'markdown-converter', name: 'Markdown Converter', icon: FileText, category: 'converters', description: 'Convert Markdown to HTML' },
  { id: 'yaml-converter', name: 'YAML Converter', icon: FileText, category: 'converters', description: 'Convert between YAML, JSON, and XML' },
  { id: 'sql-formatter', name: 'SQL Formatter', icon: Database, category: 'database', description: 'Format and beautify SQL queries' },
  { id: 'xml-formatter', name: 'XML Formatter', icon: FileCode, category: 'converters', description: 'Format and validate XML documents' },
  { id: 'password-strength', name: 'Password Strength', icon: Shield, category: 'security', description: 'Check password strength and security' },
  { id: 'unit-converter', name: 'Unit Converter', icon: Calculator, category: 'converters', description: 'Convert between various units' },
  { id: 'text-statistics', name: 'Text Statistics', icon: BarChart, category: 'text', description: 'Analyze text statistics and readability' },
  { id: 'text-encoder', name: 'Text Encoder', icon: FileCode2, category: 'text', description: 'Encode/decode text in various formats' },
  { id: 'text-replacer', name: 'Text Replacer', icon: Replace, category: 'text', description: 'Find and replace text with patterns' },
  { id: 'line-tools', name: 'Line Tools', icon: List, category: 'text', description: 'Sort, deduplicate, and manipulate lines' },
  { id: 'text-splitter', name: 'Text Splitter', icon: Scissors, category: 'text', description: 'Split text by various criteria' },
  { id: 'character-counter', name: 'Character Counter', icon: Calculator, category: 'text', description: 'Count characters, words, and lines' },
  { id: 'markdown-to-html', name: 'Markdown to HTML', icon: FileText, category: 'text', description: 'Convert Markdown to HTML live' },
  { id: 'database-schema-visualizer', name: 'Schema Visualizer', icon: Database, category: 'database', description: 'Visualize database schemas as ERD' },
  { id: 'sql-query-builder', name: 'Query Builder', icon: Table, category: 'database', description: 'Build SQL queries visually' },
  { id: 'connection-string-builder', name: 'Connection String', icon: LinkIcon, category: 'database', description: 'Build database connection strings' },
  { id: 'mock-data-generator', name: 'Mock Data', icon: Database, category: 'database', description: 'Generate realistic test data' },
  { id: 'ssl-certificate-analyzer', name: 'SSL Certificate', icon: Shield, category: 'security', description: 'Analyze SSL certificates' },
  { id: 'encryption-tools', name: 'Encryption', icon: Lock, category: 'security', description: 'Encrypt and decrypt data' }, 
  { id: 'hmac-generator', name: 'HMAC Generator', icon: Key, category: 'security', description: 'Generate HMAC authentication codes' },
  { id: 'certificate-decoder', name: 'Certificate Decoder', icon: FileKey, category: 'security', description: 'Decode X.509 certificates' },
  { id: 'file-checksum-calculator', name: 'File Checksum', icon: Hash, category: 'file', description: 'Calculate file checksums' },
  { id: 'file-sum-calculator', name: 'File Analyzer', icon: BarChart, category: 'file', description: 'Analyze file properties' },
  { id: 'secure-zip-viewer', name: 'ZIP Viewer', icon: Archive, category: 'file', description: 'View ZIP archive contents securely' },
  { id: 'image-converter', name: 'Image Converter', icon: FileImage, category: 'file', description: 'Convert between image formats' },
  { id: 'code-minifier', name: 'Code Minifier', icon: FileCode, category: 'converters', description: 'Minify JavaScript, CSS, and HTML' },
  { id: 'svg-optimizer', name: 'SVG Optimizer', icon: FileImage, category: 'file', description: 'Optimize SVG files' },
  { id: 'cron-expression-builder', name: 'Cron Builder', icon: Clock, category: 'generators', description: 'Build cron expressions visually' },
];

export const categories = {
  featured: 'Featured',
  converters: 'Data Converters',
  validation: 'Validation & Debug',
  generators: 'Generators',
  network: 'API & Network',
  design: 'CSS & Design',
  text: 'Text Processing',
  database: 'Database Tools',
  security: 'Security & Encryption',
  file: 'File Tools'
};

// Color scheme for categories
export const categoryColors = {
  featured: 'text-purple-500 dark:text-purple-400',
  converters: 'text-blue-500 dark:text-blue-400',
  validation: 'text-green-500 dark:text-green-400',
  generators: 'text-pink-500 dark:text-pink-400',
  network: 'text-orange-500 dark:text-orange-400',
  design: 'text-indigo-500 dark:text-indigo-400',
  text: 'text-teal-500 dark:text-teal-400',
  database: 'text-yellow-500 dark:text-yellow-400',
  security: 'text-red-500 dark:text-red-400',
  file: 'text-cyan-500 dark:text-cyan-400'
};

// Helper function to get tool by ID
export const getToolById = (id: string) => {
  return tools.find(tool => tool.id === id);
};